# Generated by Django 3.2.8 on 2021-11-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('authority', models.PositiveSmallIntegerField(choices=[(1, 'TA'), (2, 'instructor'), (3, 'administrator')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('description', models.CharField(max_length=5000, verbose_name='Course Description')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.account')),
            ],
        ),
    ]
