# Generated by Django 3.2.10 on 2021-12-13 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Account ID"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Course ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Course Name")),
                (
                    "description",
                    models.CharField(
                        max_length=5000, verbose_name="Course Description"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructors",
                        to="TA_Scheduler.account",
                    ),
                ),
                (
                    "tas",
                    models.ManyToManyField(
                        blank=True, related_name="tas", to="TA_Scheduler.Account"
                    ),
                ),
            ],
        ),
    ]
