# Generated by Django 3.2.8 on 2021-12-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TA_Scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="authority",
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="TA_Scheduler.account",
            ),
        ),
    ]
