# Generated by Django 3.2.9 on 2021-12-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TA_Scheduler", "0001_initial"),
    ]

    operations = []
