# Generated by Django 3.2.9 on 2021-12-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0002_alter_course_instructor'),
        ('TA_Scheduler', '0002_auto_20211203_2135'),
    ]

    operations = [
    ]
