# Generated by Django 3.2.9 on 2021-12-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0003_merge_20211205_0358'),
        ('TA_Scheduler', '0003_merge_20211205_1144'),
    ]

    operations = [
    ]
