name: Model Graph CI

on:
  push:
    branches: [ docs/models ]
  pull_request:
    branches: [ docs/models ]

jobs:
  # This workflow contains a single job called "generate-docs"
  generate-docs:
    # Check if the PR is not from a fork
    #if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Graphviz
        run: |
          sudo apt install graphviz

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Migrate DB
        run: |
          python manage.py makemigrations --merge
          python manage.py migrate


      - name: Generate pdf and svg
        run: |
          python manage.py graph_models -a -o "docs/models/CS361Group3Project.pdf"
          python manage.py graph_models -a -o "docs/models/CS361Group3Project.svg"

      - name: sanity check
        run: ls docs/models

      - name: Add new files
        run: git add .

      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'John Schiltz'
          git config --global user.email '45466247+schiltz3@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Built graphs for current models in docs\models"
          git push
