name: Model Graph CI

on:
  push:
    branches: [ docs/models ]
  pull_request:
    branches: [ docs/models ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Graphviz
        run: |
          sudo apt install graphviz
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate pdf and svg
        run: |
          python manage.py graph_models -a -o docs\models\CS361Group3Project.pdf
          python manage.py graph_models -a -o docs\models\CS361Group3Project.svg
